apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "turbo.labels" . | nindent 4 }}
    {{- include "turbo.frontend.selectorLabels" . | nindent 4 }}
